# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "develop" ]
  #pull_request:
    #branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test
      - name: Run Coverage
        run: npm run coverage
 
  merge-to-main:
    needs: build
    runs-on: ubuntu-latest
    #if: github.ref == 'refs/heads/ft'
    steps:
      #- uses: actions/checkout@v3
      - name: Merge to main
        if: ${{ success() }}
        run: |
          git config --global user.name "CIBot"
          git config --global user.email "cibot@gmail.com"
          git fetch origin main
          git rev-parse origin/develop
          git rev-parse develop
          echo "-----------------"
          git checkout -b main origin/main
          git rev-parse origin/main
          git rev-parse main
          git merge --ff develop -X theirs 
          git status
          echo "-----------------"
          git push "HEAD:main"

      - name: Move rejected commits
        if: ${{ failure() }}
        run: |
          if git show-ref --verify --quiet "refs/heads/rejected/no_build"; then
            git branch -d rejected/no_build
          fi
          git checkout -b rejected/no_build
          git push -u origin rejected/no_build